In [1]:
import os, sys, random, shutil
import xml.etree.ElementTree as ET
from glob import glob
import pandas as pd
from shutil import copyfile
import pandas as pd
from sklearn import preprocessing, model_selection
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import patches
import numpy as np


In [18]:
annotations = sorted(glob('/home/karush/code/karushp/project-helmet-det/helmet_det/data/VOC2028/Annotations/*.xml'))

In [3]:
len(annotations)

7581

In [20]:
df = []
cnt = 0
for file in annotations:
  prev_filename = file.split('/')[-1].split('.')[0] + '.jpg'
  filename = str(cnt) + '.jpg'
  row = []
  parsedXML = ET.parse(file)
  for node in parsedXML.getroot().iter('object'):
    blood_cells = node.find('name').text
    xmin = int(node.find('bndbox/xmin').text)
    xmax = int(node.find('bndbox/xmax').text)
    ymin = int(node.find('bndbox/ymin').text)
    ymax = int(node.find('bndbox/ymax').text)

    row = [prev_filename, filename, blood_cells, xmin, xmax, ymin, ymax]
    df.append(row)
  cnt += 1

data = pd.DataFrame(df, columns=['prev_filename', 'filename', 'cell_type', 'xmin', 'xmax', 'ymin', 'ymax'])


In [21]:

data[['prev_filename','filename', 'cell_type', 'xmin', 'xmax', 'ymin', 'ymax']].to_csv('/home/karush/code/karushp/project-helmet-det/helmet_det/data/output.csv', index=False)
data.head(10)

prev_filename filename cell_type  xmin  xmax  ymin  ymax
0    000000.jpg    0.jpg       hat    60   910    66  1108
1    000002.jpg    1.jpg       hat    37    76    32    84
2    000002.jpg    1.jpg       hat    97   125    44    82
3    000002.jpg    1.jpg       hat   165   208   103   158
4    000002.jpg    1.jpg       hat   178   213    71   113
5    000002.jpg    1.jpg       hat   221   251    44    88
6    000002.jpg    1.jpg       hat   249   283    61   112
7    000002.jpg    1.jpg       hat   335   376    60   112
8    000002.jpg    1.jpg       hat   344   385   107   163
9    000002.jpg    1.jpg       hat   372   402    59   110

In [22]:
img_width = 640
img_height = 480

def width(df):
  return int(df.xmax - df.xmin)
def height(df):
  return int(df.ymax - df.ymin)
def x_center(df):
  return int(df.xmin + (df.width/2))
def y_center(df):
  return int(df.ymin + (df.height/2))
def w_norm(df):
  return df/img_width
def h_norm(df):
  return df/img_height

df = pd.read_csv('/home/karush/code/karushp/project-helmet-det/helmet_det/data/output.csv')

le = preprocessing.LabelEncoder()
le.fit(df['cell_type'])
print(le.classes_)
labels = le.transform(df['cell_type'])
df['labels'] = labels

df['width'] = df.apply(width, axis=1)
df['height'] = df.apply(height, axis=1)

df['x_center'] = df.apply(x_center, axis=1)
df['y_center'] = df.apply(y_center, axis=1)

df['x_center_norm'] = df['x_center'].apply(w_norm)
df['width_norm'] = df['width'].apply(w_norm)

df['y_center_norm'] = df['y_center'].apply(h_norm)
df['height_norm'] = df['height'].apply(h_norm)

df.head(30)

['dog' 'hat' 'person']


prev_filename filename cell_type  xmin  xmax  ymin  ymax  labels  width  \
0     000000.jpg    0.jpg       hat    60   910    66  1108       1    850   
1     000002.jpg    1.jpg       hat    37    76    32    84       1     39   
2     000002.jpg    1.jpg       hat    97   125    44    82       1     28   
3     000002.jpg    1.jpg       hat   165   208   103   158       1     43   
4     000002.jpg    1.jpg       hat   178   213    71   113       1     35   
5     000002.jpg    1.jpg       hat   221   251    44    88       1     30   
6     000002.jpg    1.jpg       hat   249   283    61   112       1     34   
7     000002.jpg    1.jpg       hat   335   376    60   112       1     41   
8     000002.jpg    1.jpg       hat   344   385   107   163       1     41   
9     000002.jpg    1.jpg       hat   372   402    59   110       1     30   
10    000002.jpg    1.jpg       hat   409   454    77   136       1     45   
11    000002.jpg    1.jpg    person     9    46    75   124       2     37   
12    000003.jpg    2.jpg       hat    58   125    20    73       1     67   
13    000003.jpg    2.jpg       hat   242   282    69   125       1     40   
14    000003.jpg    2.jpg       hat   282   324    69   128       1     42   
15    000003.jpg    2.jpg       hat   313   363    49   120       1     50   
16    000003.jpg    2.jpg    person   152   241    38   132       2     89   
17    000003.jpg    2.jpg    person   297   423   114   257       2    126   
18    000003.jpg    2.jpg    person   348   424    47   124       2     76   
19    000004.jpg    3.jpg       hat   366   410    79   124       1     44   
20    000004.jpg    3.jpg    person   437   477    33    69       2     40   
21    000004.jpg    3.jpg    person   420   444    91   123       2     24   
22    000005.jpg    4.jpg       hat   378   458   109   179       1     80   
23    000006.jpg    5.jpg       hat   129   154   191   219       1     25   
24    000006.jpg    5.jpg       hat   244   285   112   157       1     41   
25    000006.jpg    5.jpg       hat   425   500     1    69       1     75   
26    000006.jpg    5.jpg       hat    93   104   242   255       1     11   
27    000006.jpg    5.jpg       hat    69    81   243   255       1     12   
28    000006.jpg    5.jpg       hat    53    62   245   257       1      9   
29    000006.jpg    5.jpg    person    61    67   248   257       2      6   

    height  x_center  y_center  x_center_norm  width_norm  y_center_norm  \
0     1042       485       587       0.757812    1.328125       1.222917   
1       52        56        58       0.087500    0.060937       0.120833   
2       38       111        63       0.173437    0.043750       0.131250   
3       55       186       130       0.290625    0.067187       0.270833   
4       42       195        92       0.304688    0.054688       0.191667   
5       44       236        66       0.368750    0.046875       0.137500   
6       51       266        86       0.415625    0.053125       0.179167   
7       52       355        86       0.554688    0.064062       0.179167   
8       56       364       135       0.568750    0.064062       0.281250   
9       51       387        84       0.604688    0.046875       0.175000   
10      59       431       106       0.673438    0.070312       0.220833   
11      49        27        99       0.042188    0.057813       0.206250   
12      53        91        46       0.142187    0.104688       0.095833   
13      56       262        97       0.409375    0.062500       0.202083   
14      59       303        98       0.473438    0.065625       0.204167   
15      71       338        84       0.528125    0.078125       0.175000   
16      94       196        85       0.306250    0.139063       0.177083   
17     143       360       185       0.562500    0.196875       0.385417   
18      77       386        85       0.603125    0.118750       0.177083   
19      45       388       101       0.606250    0.068750       

In [4]:
df = []
cnt = 0
for file in annotations:
  prev_filename = file.split('/')[-1].split('.')[0] + '.jpg'
  filename = str(cnt) + '.jpg'
  row = []
  parsedXML = ET.parse(file)
  for node in parsedXML.getroot().iter('object'):
    search_type = node.find('name').text
    xmin = int(node.find('bndbox/xmin').text)
    xmax = int(node.find('bndbox/xmax').text)
    ymin = int(node.find('bndbox/ymin').text)
    ymax = int(node.find('bndbox/ymax').text)

    row = [prev_filename, filename, search_type, xmin, xmax, ymin, ymax]
    df.append(row)
  cnt += 1


In [5]:
data = pd.DataFrame(df, columns=['prev_filename', 'filename', 'search_type', 'xmin', 'xmax', 'ymin', 'ymax'])


In [6]:
data.shape

(120561, 7)

In [7]:
data.head()

prev_filename filename search_type  xmin  xmax  ymin  ymax
0    000000.jpg    0.jpg         hat    60   910    66  1108
1    000002.jpg    1.jpg         hat    37    76    32    84
2    000002.jpg    1.jpg         hat    97   125    44    82
3    000002.jpg    1.jpg         hat   165   208   103   158
4    000002.jpg    1.jpg         hat   178   213    71   113

In [8]:
data[['prev_filename','filename', 'search_type', 'xmin', 'xmax', 'ymin', 'ymax']].to_csv('/home/karush/code/karushp/project-helmet-det/helmet_det/data/output.csv', index=False)


In [9]:
img_width = 640
img_height = 480

def width(df):
  return int(df.xmax - df.xmin)
def height(df):
  return int(df.ymax - df.ymin)
def x_center(df):
  return int(df.xmin + (df.width/2))
def y_center(df):
  return int(df.ymin + (df.height/2))
def w_norm(df):
  return df/img_width
def h_norm(df):
  return df/img_height

df = pd.read_csv('/home/karush/code/karushp/project-helmet-det/helmet_det/data/output.csv')

le = preprocessing.LabelEncoder()
le.fit(df['search_type'])
print(le.classes_)
labels = le.transform(df['search_type'])
df['labels'] = labels

df['width'] = df.apply(width, axis=1)
df['height'] = df.apply(height, axis=1)

df['x_center'] = df.apply(x_center, axis=1)
df['y_center'] = df.apply(y_center, axis=1)

df['x_center_norm'] = df['x_center'].apply(w_norm)
df['width_norm'] = df['width'].apply(w_norm)

df['y_center_norm'] = df['y_center'].apply(h_norm)
df['height_norm'] = df['height'].apply(h_norm)

df.head(10)

['dog' 'hat' 'person']


prev_filename filename search_type  xmin  xmax  ymin  ymax  labels  width  \
0    000000.jpg    0.jpg         hat    60   910    66  1108       1    850   
1    000002.jpg    1.jpg         hat    37    76    32    84       1     39   
2    000002.jpg    1.jpg         hat    97   125    44    82       1     28   
3    000002.jpg    1.jpg         hat   165   208   103   158       1     43   
4    000002.jpg    1.jpg         hat   178   213    71   113       1     35   
5    000002.jpg    1.jpg         hat   221   251    44    88       1     30   
6    000002.jpg    1.jpg         hat   249   283    61   112       1     34   
7    000002.jpg    1.jpg         hat   335   376    60   112       1     41   
8    000002.jpg    1.jpg         hat   344   385   107   163       1     41   
9    000002.jpg    1.jpg         hat   372   402    59   110       1     30   

   height  x_center  y_center  x_center_norm  width_norm  y_center_norm  \
0    1042       485       587       0.757812    1.328125       1.222917   
1      52        56        58       0.087500    0.060937       0.120833   
2      38       111        63       0.173437    0.043750       0.131250   
3      55       186       130       0.290625    0.067187       0.270833   
4      42       195        92       0.304688    0.054688       0.191667   
5      44       236        66       0.368750    0.046875       0.137500   
6      51       266        86       0.415625    0.053125       0.179167   
7      52       355        86       0.554688    0.064062       0.179167   
8      56       364       135       0.568750    0.064062       0.281250   
9      51       387        84       0.604688    0.046875       0.175000   

   height_norm  
0     2.170833  
1     0.108333  
2     0.079167  
3     0.114583  
4     0.087500  
5     0.091667  
6     0.106250  
7     0.108333  
8     0.116667  
9     0.106250

In [23]:
# First split: 80% train, 20% temporary (which will be split into validation and test)
df_train, df_temp = model_selection.train_test_split(df, test_size=0.2, random_state=13, shuffle=True)

# Second split: 50% of temporary set for validation and 50% for test (resulting in 10% each of the original dataset)
df_valid, df_test = model_selection.train_test_split(df_temp, test_size=0.5, random_state=13, shuffle=True)

# Output the sizes to verify the splits
print(f'Training set size: {len(df_train)}')
print(f'Validation set size: {len(df_valid)}')
print(f'Test set size: {len(df_test)}')

Training set size: 96448
Validation set size: 12056
Test set size: 12057


In [24]:
# creating directory for Train , Val and Test folders

# for images
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/train/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/valid/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/test/')

# for labels
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/train/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/valid/')
os.mkdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/test/')

In [25]:
# function to segregate_data
def segregate_data(df, img_path, label_path, train_img_path, train_label_path):
  filenames = []
  for filename in df.filename:
    filenames.append(filename)
  filenames = set(filenames)

  for filename in filenames:
    yolo_list = []

    for _,row in df[df.filename == filename].iterrows():
      yolo_list.append([row.labels, row.x_center_norm, row.y_center_norm, row.width_norm, row.height_norm])

    yolo_list = np.array(yolo_list)
    #print(yolo_list)
    txt_filename = os.path.join(train_label_path,str(row.prev_filename.split('.')[0])+".txt")
    #print(txt_filename)

    # Save the .img & .txt files to the corresponding train and validation folders
    np.savetxt(txt_filename, yolo_list, fmt=["%d", "%f", "%f", "%f", "%f"])
    shutil.copyfile(os.path.join(img_path,row.prev_filename), os.path.join(train_img_path,row.prev_filename))

In [26]:
## Apply function ##
src_img_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/VOC2028/JPEGImages'
src_label_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/VOC2028/Annotations'

train_img_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/train/'
train_label_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/train/'

valid_img_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/valid/'
valid_label_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/valid/'

test_img_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/test/'
test_label_path = '/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/test/'

segregate_data(df_train, src_img_path, src_label_path, train_img_path, train_label_path)
#segregate_data(df_valid, src_img_path, src_label_path, valid_img_path, valid_label_path)
#segregate_data(df_test, src_img_path, src_label_path, test_img_path, test_label_path)


[[2.         1.38125    1.06666667 0.1296875  0.18958333]
 [2.         1.23125    0.8        0.084375   0.13541667]
 [2.         0.9625     0.59375    0.0859375  0.13333333]
 [2.         0.2046875  0.87916667 0.090625   0.14791667]
 [2.         0.5671875  0.78958333 0.115625   0.14166667]
 [2.         0.5859375  1.35833333 0.3328125  0.36458333]
 [2.         0.290625   0.8375     0.0984375  0.14166667]
 [2.         1.45625    0.87083333 0.0984375  0.15      ]
 [2.         0.5453125  0.9625     0.1171875  0.19583333]
 [2.         1.346875   0.83958333 0.1234375  0.17083333]
 [2.         0.44375    1.03333333 0.221875   0.3125    ]
 [2.         0.0828125  0.98125    0.1375     0.20208333]]
/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/train/PartB_00256.txt
[[2.         0.1515625  0.27708333 0.0296875  0.03125   ]
 [2.         0.3078125  0.33541667 0.034375   0.0625    ]
 [2.         0.4484375  0.38125    0.0609375  0.08958333]
 [2.         0.75625    0.34

FileNotFoundError: [Errno 2] No such file or directory: '/home/karush/code/karushp/project-helmet-det/helmet_det/data/VOC2028/JPEGImages/001331.jpg'

In [ ]:
print("No. of Training images", len(os.listdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/train/')))
print("No. of Training labels", len(os.listdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/train/')))

print("No. of valid images", len(os.listdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/valid/')))
print("No. of valid labels", len(os.listdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/valid/')))

print("No. of test images", len(os.listdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/images/test/')))
print("No. of test labels", len(os.listdir('/home/karush/code/karushp/project-helmet-det/helmet_det/data/data_split/labels/test/')))


No. of Training images 34
No. of Training labels 35
No. of valid images 0
No. of valid labels 0
No. of test images 0
No. of test labels 0
